default_install_hook_types: [ pre-commit, commit-msg ]
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Get the latest version from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
        exclude: \.key$
        stages:
          - pre-commit
      - id: end-of-file-fixer
        exclude: \.key$
        stages:
          - pre-commit
      - id: check-yaml
        args: [ --allow-multiple-documents ]
        stages:
          - pre-commit
      - id: check-added-large-files
        stages:
          - pre-commit
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.5 # Grab latest version from https://github.com/commitizen-tools/commitizen/tags
    hooks:
      - id: commitizen
        name: Commit Zen
        stages: [ commit-msg ]
  - repo: local
    hooks:
      - id: ktlint-format
        name: Kotlin Linter Format
        entry: ./gradlew ktlintFormat
        language: system
        files: \.(kt|kts)$
        pass_filenames: false
        stages:
          - pre-commit
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language: python
        stages: [ pre-commit ]
        args: [ 'secret', 'scan', 'pre-commit' ]
